### PR TITLE
#15 - Create Callout Component

### LINKED ISSUE #15: Create Callout Content Component
### Overview

This component draws the viewers attention to an important statement.  It isn't interactive, and can be used anywhere on the site.

### Lofi Mockup

https://www.radix-ui.com/themes/docs/components/callout

### Data

The callout should support the following properties:

- icon - Will need a custom icon input for https://www.radix-ui.com/icons
- text
- size
- variant

Other properties like `color` should be implemented comprehensively later across all Radix layout components.

### Category

Content

### Features

- [X] Editors can place this component in the layout.
- [X] Editors can set custom fields for this component.
- [ ] This component relies on data from an external source.
- [ ] This component is only visible to Editors and Admins.
- [ ] This component is interactive.

### Additional Support

- [ ] Research
- [ ] Content Creation (text, graphics, etc)
- [ ] Translation
- [ ] Design (UI/UX)
- [ ] Custom Editor Fields (content input)
- [ ] Integration with External Services / Data Sources
- [ ] Project Maintenance (Github, production infra, processes, etc)
- [ ] Fundraising (larger servers, external service fees, etc)

### Questions?

_No response_

### Inspiration

_No response_

### Impact

_No response_

### Relation to DA

- [X] User - I use DA's projects in my own learning, research, or work.
- [X] Contributor - I volunteer with DA or contribute to it's projects.
- [ ] Beneficiary - I recieve aid that was delivered to frontline distribution groups by DA.
- [ ] Aid Group - I volunteer with a community group that uses DA to send or receive aid.
- [ ] Partner - I work at a DA partner, service provider, or in-kind aid donor.
- [ ] Donor - I donate to DA, or my company sponsors them.
- [ ] Other - None of these options describe my relation to DA.
- [ ] None - This is my first time engaging with DA.

### Followup

- [X] Contribute content or code to help resolve this issue.
- [X] Review & test the changes to help decide if the issue is resolved.
- [ ] Donate to help maintain this project.
- [X] Receive a notification when this issue is resolved and the changes are live.
- [ ] Continue to make other contributions to DA's projects, or join DA as a committed volunteer.
- [ ] Recieve more information about DA and this project.
- [ ] After submitting this issue, I do not wish to engage with DA further or recieve any additional followup.

### IP Ownership

The materials are available under an open-source / open-content license (MIT, Creative Commons, etc).

### Ownership Details

Radix-Theme is available under an MIT license: https://github.com/radix-ui/themes/blob/main/LICENSE

Radix-Icons is available under an MIT license: https://github.com/radix-ui/icons/blob/master/LICENSE

### Attestations & Copyright Assignment

- [X] To assign Distribute Aid the copyright of any materials you created specifically for this project.
- [X] That Distribute Aid has the rights to use any materials you submit which were created by you or others for general use.
- [X] That you have specified any additional licensing requirements related to the materials (crediting the original creators, licensing fees, etc).
- [X] That the materials are not also encumbered by a patent or other types of intellectual property that limit our ability to use them.

### Code of Conduct

- [X] I agree to follow Distribute Aid's Code of Conduct.

### PR DESCRIPTION
**Pull request by jtfairbank**
Resolves #15

### CODE REVIEW

**Comment by jtfairbank** [comment]
@akuankka128 want to review this one for me? :pray:

**Review by akuankka128 — APPROVED** [review]
Approved for merging

**Comment by jtfairbank** [comment]
@akuankka128 awesome, thank you so much!  Btw if you approve a review and all the checks are passing then you can go ahead and smash the "Rebase and Merge" button yourself if you want!

**Comment by akuankka128** [comment]
> @akuankka128 awesome, thank you so much! Btw if you approve a review and all the checks are passing then you can go ahead and smash the "Rebase and Merge" button yourself if you want!

Okay, gotcha!

**Pull request merged**
